# Imports

In [ ]:
import pandas as pd 
import json
import re
from ast import literal_eval
import requests
import datetime
import time
from sklearn.model_selection import train_test_split
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
from sklearn.model_selection import GridSearchCV
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

# Methods

In [10]:
def camel_to_snake(camel_strings):
    snake_strings = []
    
    for string in camel_strings:
        temp = re.sub(r'(?<!^)(?=[A-Z])', '_', string).lower()
        snake_strings.append(temp)
        
    return snake_strings

# Importing Files

In [11]:
with open('spotify_history/others/Marquee.json', 'r', encoding='utf-8') as f:
    marquee_json = json.load(f)
    
marquee = pd.json_normalize(marquee_json)

marquee.columns = camel_to_snake(marquee.columns)
marquee = marquee.drop_duplicates()

marquee.head()

     artist_name                      segment
0         Cobrah  Previously Active Listeners
1      BLACKPINK  Previously Active Listeners
2  Martin Garrix  Previously Active Listeners
3       Confetti  Previously Active Listeners
4    Demi Lovato  Previously Active Listeners

In [12]:
with open('spotify_history/others/Playlist1.json', 'r', encoding='utf-8') as f:
    playlist_json = json.load(f)

# 2. Normalize as usual
all_playlists = []
for i in playlist_json["playlists"]:
    i_playlist = pd.json_normalize(i["items"],sep='_')
    i_playlist["playlists_lastModifiedDate"] = i["lastModifiedDate"]
    i_playlist["playlists_name"] = i["name"]
    all_playlists.append(i_playlist)

playlist = pd.concat(all_playlists)
playlist.columns = camel_to_snake(playlist.columns)
playlist = playlist.drop_duplicates()
playlist.head()

,episode,audiobook,local_track,added_date,track_track_name,track_artist_name,track_album_name,track_track_uri,track,episode_episode_name,episode_show_name,episode_episode_uri,playlists_last_modified_date,playlists_name
0,NaN,None,None,2024-10-22,Angry Too,Lola Blanc,Angry Too,spotify:track:51jK7uI2QR8JCP4G9DnbQS,NaN,NaN,NaN,NaN,2026-01-18,<3
1,NaN,None,None,2024-10-22,Walls Could Talk,Halsey,hopeless fountain kingdom,spotify:track:1Ao5nOuAUm42ob1UVvOkgW,NaN,NaN,NaN,NaN,2026-01-18,<3
2,NaN,None,None,2024-10-22,Freak (feat. REI AMI),Sub Urban,Thrill Seeker,spotify:track:5jkbw3FDS3bSSb4oLKYbjf,NaN,NaN,NaN,NaN,2026-01-18,<3
3,NaN,None,None,2024-10-22,Shameless,Camila Cabello,Romance,spotify:track:2ogKhhoMClkFXek7ZgxAhN,NaN,NaN,NaN,NaN,2026-01-18,<3
4,NaN,None,None,2024-10-22,Looking at Me,Sabrina Carpenter,Singular Act II,spotify:track:59tskctgqUmjCWAwhzYAFm,NaN,NaN,NaN,NaN,2026-01-18,<3

In [13]:
with open('spotify_history/others/YourLibrary.json', 'r', encoding='utf-8') as f:
    library_json = json.load(f)

# 2. Normalize as usual
library = pd.json_normalize(library_json, record_path=['tracks'], sep='_')

library.columns = camel_to_snake(library.columns)
library = library.drop_duplicates()

library.head()

,artist,album,track,uri
0,Set It Off,Wolf In Sheep's Clothing [REBORN],Wolf In Sheep's Clothing [REBORN],spotify:track:1tpidJ4FBn9TwshePh1bc3
1,Skillet,Awake,Monster,spotify:track:2UREu1Y8CO4jXkbvqAtP7g
2,Thousand Foot Krutch,The End Is Where We Begin,Courtesy Call,spotify:track:0AOmbw8AwDnwXhHC3OhdVB

In [14]:
with open('spotify_history/music_history/Streaming_History_Audio_2020-2026.json', 'r', encoding='utf-8') as f:
    history_json = json.load(f)

# 2. Normalize as usual
history = pd.json_normalize(history_json, sep='_')

history.columns = camel_to_snake(history.columns)
history = history.drop_duplicates()

history.head()

,ts,platform,ms_played,conn_country,ip_addr,master_metadata_track_name,master_metadata_album_artist_name,master_metadata_album_album_name,spotify_track_uri,episode_name,...,audiobook_uri,audiobook_chapter_uri,audiobook_chapter_title,reason_start,reason_end,shuffle,skipped,offline,offline_timestamp,incognito_mode
0,2020-10-20T19:36:53Z,"Android OS 10 API 29 (samsung, SM-A307GT)",23600,BR,177.58.181.120,Pretty Savage,BLACKPINK,THE ALBUM,spotify:track:1XnpzbOGptRwfJhZgLbmSr,NaN,...,None,None,None,clickrow,backbtn,False,False,False,NaN,False
1,2020-10-20T19:36:55Z,"Android OS 10 API 29 (samsung, SM-A307GT)",1052,BR,177.58.181.120,How You Like That,BLACKPINK,THE ALBUM,spotify:track:4SFknyjLcyTLJFPKD2m96o,NaN,...,None,None,None,backbtn,backbtn,False,False,False,NaN,False
2,2020-10-20T19:36:56Z,"Android OS 10 API 29 (samsung, SM-A307GT)",0,BR,177.58.181.120,Ice Cream (with Selena Gomez),BLACKPINK,THE ALBUM,spotify:track:4JUPEh2DVSXFGExu4Uxevz,NaN,...,None,None,None,backbtn,backbtn,False,False,False,NaN,False
3,2020-10-20T19:36:56Z,"Android OS 10 API 29 (samsung, SM-A307GT)",0,BR,177.58.181.120,Bet You Wanna (feat. Cardi B),BLACKPINK,THE ALBUM,spotify:track:7iAgNZdotu40NwtoIWJHFe,NaN,...,None,None,None,backbtn,backbtn,False,False,False,NaN,False
4,2020-10-20T19:36:59Z,"Android OS 10 API 29 (samsung, SM-A307GT)",1824,BR,177.58.181.120,Lovesick Girls,BLACKPINK,THE ALBUM,spotify:track:4Ws314Ylb27BVsvlZOy30C,NaN,...,None,None,None,backbtn,fwdbtn,False,False,False,NaN,False

# Creating the main table

In [15]:
# joining history df with marquee df
final_df = pd.merge(history, marquee, how='left', left_on='master_metadata_album_artist_name', right_on='artist_name').drop(columns=['master_metadata_album_artist_name'])

# adding column in_playlist
final_df['in_playlist'] = final_df['spotify_track_uri'].isin(playlist['track_track_uri'])

# adding column in_library
final_df['in_library'] = final_df['spotify_track_uri'].isin(library['uri'])

final_df["track_id"] = final_df["spotify_track_uri"].str.rpartition(":")[2]

# dropping null values in spotify_track_uri, tracks that are podcasts
final_df = final_df.dropna(subset=["spotify_track_uri"])

final_df.to_csv("final_df.csv", index=False)
final_df

,ts,platform,ms_played,conn_country,ip_addr,master_metadata_track_name,master_metadata_album_album_name,spotify_track_uri,episode_name,episode_show_name,...,shuffle,skipped,offline,offline_timestamp,incognito_mode,artist_name,segment,in_playlist,in_library,track_id
0,2020-10-20T19:36:53Z,"Android OS 10 API 29 (samsung, SM-A307GT)",23600,BR,177.58.181.120,Pretty Savage,THE ALBUM,spotify:track:1XnpzbOGptRwfJhZgLbmSr,NaN,NaN,...,False,False,False,NaN,False,BLACKPINK,Previously Active Listeners,False,False,1XnpzbOGptRwfJhZgLbmSr
1,2020-10-20T19:36:55Z,"Android OS 10 API 29 (samsung, SM-A307GT)",1052,BR,177.58.181.120,How You Like That,THE ALBUM,spotify:track:4SFknyjLcyTLJFPKD2m96o,NaN,NaN,...,False,False,False,NaN,False,BLACKPINK,Previously Active Listeners,False,False,4SFknyjLcyTLJFPKD2m96o
2,2020-10-20T19:36:56Z,"Android OS 10 API 29 (samsung, SM-A307GT)",0,BR,177.58.181.120,Ice Cream (with Selena Gomez),THE ALBUM,spotify:track:4JUPEh2DVSXFGExu4Uxevz,NaN,NaN,...,False,False,False,NaN,False,BLACKPINK,Previously Active Listeners,False,False,4JUPEh2DVSXFGExu4Uxevz
3,2020-10-20T19:36:56Z,"Android OS 10 API 29 (samsung, SM-A307GT)",0,BR,177.58.181.120,Bet You Wanna (feat. Cardi B),THE ALBUM,spotify:track:7iAgNZdotu40NwtoIWJHFe,NaN,NaN,...,False,False,False,NaN,False,BLACKPINK,Previously Active Listeners,False,False,7iAgNZdotu40NwtoIWJHFe
4,2020-10-20T19:36:59Z,"Android OS 10 API 29 (samsung, SM-A307GT)",1824,BR,177.58.181.120,Lovesick Girls,THE ALBUM,spotify:track:4Ws314Ylb27BVsvlZOy30C,NaN,NaN,...,False,False,False,NaN,False,BLACKPINK,Previously Active Listeners,False,False,4Ws314Ylb27BVsvlZOy30C
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7394,2026-01-22T20:51:55Z,ios,201760,BR,2804:7f0:b2c1:40d5:9512:4b9f:c178:1ce0,Hungarian Dance No. 5 (Brahms),Brahms: Hungarian Dances for string orchestra,spotify:track:2dvrarYDL3flRy9ESkqvKK,NaN,NaN,...,True,False,False,1.769115e+09,False,NaN,NaN,False,False,2dvrarYDL3flRy9ESkqvKK
7395,2026-01-22T20:56:53Z,ios,296853,BR,2804:7f0:b2c1:40d5:9512:4b9f:c178:1ce0,Friska from Hungarian Rhapsody No. 2,Autobahn [Drive Time],spotify:track:3B84LG8ayDrYnfwlm11Vn4,NaN,NaN,...,True,False,False,1.769115e+09,False,NaN,NaN,False,False,3B84LG8ayDrYnfwlm11Vn4
7396,2026-01-23T03:10:40Z,ios,437017,BR,2804:7f0:b2c1:40d5:38c4:1dd8:42d3:546d,Toccata and Fugue in D minor,Great Organ Classics,spotify:track:0BWJNm4TrO6H3qgiCmDBjM,NaN,NaN,...,True,False,False,1.769115e+09,False,NaN,NaN,False,False,0BWJNm4TrO6H3qgiCmDBjM
7397,2026-01-23T13:13:29Z,ios,11685,BR,2804:38a:a08e:d9a5:7dbf:86aa:23b2:662f,Tis so Sweet to Trust in Jesus,Lullaby Hymns: The Weary Soul,spotify:track:21fL1tPW9PN7mgqhgeL7lC,NaN,NaN,...,False,True,False,1.769173e+09,False,NaN,NaN,False,False,21fL1tPW9PN7mgqhgeL7lC
7398,2026-01-24T03:50:37Z,ios,9590,BR,2804:7f0:b2c1:40d5:8950:9dc2:a0df:9123,Leaning On The Everlasting Arms / 'Tis So Swee...,Give Us Rest Or A Requiem Mass In C (The Happi...,spotify:track:2VAtZmI9nCB97Kdnn9tMIF,NaN,NaN,...,False,False,False,1.769174e+09,False,NaN,NaN,False,False,2VAtZmI9nCB97Kdnn9tMIF

In [ ]:
# creating playlist_percentage

#get total amount of playlist

playlist_amount = playlist['playlists_name'].nunique()

# 1. Get the counts of each value in df_2
counts = playlist['track_track_uri'].value_counts()

# 2. Map those counts to df_1
final_df['playlist_count'] = final_df['spotify_track_uri'].map(counts)

# 3. Fill NaNs with 0 (for values that didn't appear in df_2) and convert to integer
final_df['playlist_count'] = final_df['playlist_count'].fillna(0).astype(int)

final_df['percentage_playlists'] = final_df['playlist_count'] / playlist_amount

final_df

,ts,platform,ms_played,conn_country,ip_addr,master_metadata_track_name,master_metadata_album_album_name,spotify_track_uri,episode_name,episode_show_name,...,offline,offline_timestamp,incognito_mode,artist_name,segment,in_playlist,in_library,track_id,amount_playlists,percentage_playlists
0,2020-10-20T19:36:53Z,"Android OS 10 API 29 (samsung, SM-A307GT)",23600,BR,177.58.181.120,Pretty Savage,THE ALBUM,spotify:track:1XnpzbOGptRwfJhZgLbmSr,NaN,NaN,...,False,NaN,False,BLACKPINK,Previously Active Listeners,False,False,1XnpzbOGptRwfJhZgLbmSr,0,0.0
1,2020-10-20T19:36:55Z,"Android OS 10 API 29 (samsung, SM-A307GT)",1052,BR,177.58.181.120,How You Like That,THE ALBUM,spotify:track:4SFknyjLcyTLJFPKD2m96o,NaN,NaN,...,False,NaN,False,BLACKPINK,Previously Active Listeners,False,False,4SFknyjLcyTLJFPKD2m96o,0,0.0
2,2020-10-20T19:36:56Z,"Android OS 10 API 29 (samsung, SM-A307GT)",0,BR,177.58.181.120,Ice Cream (with Selena Gomez),THE ALBUM,spotify:track:4JUPEh2DVSXFGExu4Uxevz,NaN,NaN,...,False,NaN,False,BLACKPINK,Previously Active Listeners,False,False,4JUPEh2DVSXFGExu4Uxevz,0,0.0
3,2020-10-20T19:36:56Z,"Android OS 10 API 29 (samsung, SM-A307GT)",0,BR,177.58.181.120,Bet You Wanna (feat. Cardi B),THE ALBUM,spotify:track:7iAgNZdotu40NwtoIWJHFe,NaN,NaN,...,False,NaN,False,BLACKPINK,Previously Active Listeners,False,False,7iAgNZdotu40NwtoIWJHFe,0,0.0
4,2020-10-20T19:36:59Z,"Android OS 10 API 29 (samsung, SM-A307GT)",1824,BR,177.58.181.120,Lovesick Girls,THE ALBUM,spotify:track:4Ws314Ylb27BVsvlZOy30C,NaN,NaN,...,False,NaN,False,BLACKPINK,Previously Active Listeners,False,False,4Ws314Ylb27BVsvlZOy30C,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7394,2026-01-22T20:51:55Z,ios,201760,BR,2804:7f0:b2c1:40d5:9512:4b9f:c178:1ce0,Hungarian Dance No. 5 (Brahms),Brahms: Hungarian Dances for string orchestra,spotify:track:2dvrarYDL3flRy9ESkqvKK,NaN,NaN,...,False,1.769115e+09,False,NaN,NaN,False,False,2dvrarYDL3flRy9ESkqvKK,0,0.0
7395,2026-01-22T20:56:53Z,ios,296853,BR,2804:7f0:b2c1:40d5:9512:4b9f:c178:1ce0,Friska from Hungarian Rhapsody No. 2,Autobahn [Drive Time],spotify:track:3B84LG8ayDrYnfwlm11Vn4,NaN,NaN,...,False,1.769115e+09,False,NaN,NaN,False,False,3B84LG8ayDrYnfwlm11Vn4,0,0.0
7396,2026-01-23T03:10:40Z,ios,437017,BR,2804:7f0:b2c1:40d5:38c4:1dd8:42d3:546d,Toccata and Fugue in D minor,Great Organ Classics,spotify:track:0BWJNm4TrO6H3qgiCmDBjM,NaN,NaN,...,False,1.769115e+09,False,NaN,NaN,False,False,0BWJNm4TrO6H3qgiCmDBjM,0,0.0
7397,2026-01-23T13:13:29Z,ios,11685,BR,2804:38a:a08e:d9a5:7dbf:86aa:23b2:662f,Tis so Sweet to Trust in Jesus,Lullaby Hymns: The Weary Soul,spotify:track:21fL1tPW9PN7mgqhgeL7lC,NaN,NaN,...,False,1.769173e+09,False,NaN,NaN,False,False,21fL1tPW9PN7mgqhgeL7lC,0,0.0
7398,2026-01-24T03:50:37Z,ios,9590,BR,2804:7f0:b2c1:40d5:8950:9dc2:a0df:9123,Leaning On The Everlasting Arms / 'Tis So Swee...,Give Us Rest Or A Requiem Mass In C (The Happi...,spotify:track:2VAtZmI9nCB97Kdnn9tMIF,NaN,NaN,...,False,1.769174e+09,False,NaN,NaN,False,False,2VAtZmI9nCB97Kdnn9tMIF,0,0.0