# Imports

In [15]:
import pandas as pd
from _spo_utils import camel_to_snake, import_json

# Constants

In [16]:
PATH_SPOTIFY = '../../data/2_processed/final_df.csv'
PATH_PROCESSED = '../../data/2_processed/processed.csv'
PATH_LIBRARY = '../../spotify_history/others/YourLibrary.json'
PATH_PLAYLIST = '../../spotify_history/others/Playlist1.json'

# Getting DF

In [17]:
final_df = pd.read_csv(PATH_SPOTIFY)
final_df

,Unnamed: 0,ts,platform,ms_played,conn_country,ip_addr,master_metadata_track_name,master_metadata_album_album_name,spotify_track_uri,episode_name,...,loudness,mode,speechiness,tempo,valence,popularity,duration_ms,lat_long,temperature,precipitation
0,0,2020-10-20 19:36:53+00:00,"Android OS 10 API 29 (samsung, SM-A307GT)",23600,BR,177.58.181.120,Pretty Savage,THE ALBUM,spotify:track:1XnpzbOGptRwfJhZgLbmSr,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"-23.5,-46.3",23.00,0.8
1,1,2020-10-20 19:36:55+00:00,"Android OS 10 API 29 (samsung, SM-A307GT)",1052,BR,177.58.181.120,How You Like That,THE ALBUM,spotify:track:4SFknyjLcyTLJFPKD2m96o,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"-23.5,-46.3",23.00,0.8
2,2,2020-10-20 19:36:56+00:00,"Android OS 10 API 29 (samsung, SM-A307GT)",0,BR,177.58.181.120,Ice Cream (with Selena Gomez),THE ALBUM,spotify:track:4JUPEh2DVSXFGExu4Uxevz,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"-23.5,-46.3",23.00,0.8
3,3,2020-10-20 19:36:56+00:00,"Android OS 10 API 29 (samsung, SM-A307GT)",0,BR,177.58.181.120,Bet You Wanna (feat. Cardi B),THE ALBUM,spotify:track:7iAgNZdotu40NwtoIWJHFe,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"-23.5,-46.3",23.00,0.8
4,4,2020-10-20 19:36:59+00:00,"Android OS 10 API 29 (samsung, SM-A307GT)",1824,BR,177.58.181.120,Lovesick Girls,THE ALBUM,spotify:track:4Ws314Ylb27BVsvlZOy30C,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"-23.5,-46.3",23.00,0.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10887,10887,2026-01-22 20:56:53+00:00,ios,296853,BR,2804:7f0:b2c1:40d5:9512:4b9f:c178:1ce0,Friska from Hungarian Rhapsody No. 2,Autobahn [Drive Time],spotify:track:3B84LG8ayDrYnfwlm11Vn4,NaN,...,-13.779,1.0,0.0463,79.711,0.3600,24.0,296853.0,"-23.6,-46.6",17.55,0.3
10888,10888,2026-01-23 03:10:40+00:00,ios,437017,BR,2804:7f0:b2c1:40d5:38c4:1dd8:42d3:546d,Toccata and Fugue in D minor,Great Organ Classics,spotify:track:0BWJNm4TrO6H3qgiCmDBjM,NaN,...,-25.350,0.0,0.0373,71.749,0.0714,52.0,567466.0,"-23.6,-46.6",16.10,0.0
10889,10889,2026-01-23 13:13:29+00:00,ios,11685,BR,2804:38a:a08e:d9a5:7dbf:86aa:23b2:662f,Tis so Sweet to Trust in Jesus,Lullaby Hymns: The Weary Soul,spotify:track:21fL1tPW9PN7mgqhgeL7lC,NaN,...,-16.239,1.0,0.0323,80.077,0.1580,39.0,256653.0,"-23.5,-46.6",21.20,0.4
10890,10890,2026-01-23 13:13:29+00:00,ios,11685,BR,2804:38a:a08e:d9a5:7dbf:86aa:23b2:662f,Tis so Sweet to Trust in Jesus,Lullaby Hymns: The Weary Soul,spotify:track:21fL1tPW9PN7mgqhgeL7lC,NaN,...,-16.239,1.0,0.0323,80.077,0.1580,39.0,256653.0,"-23.5,-46.6",21.20,0.4
10891,10891,2026-01-24 03:50:37+00:00,ios,9590,BR,2804:7f0:b2c1:40d5:8950:9dc2:a0df:9123,Leaning On The Everlasting Arms / 'Tis So Swee...,Give Us Rest Or A Requiem Mass In C (The Happi...,spotify:track:2VAtZmI9nCB97Kdnn9tMIF,NaN,...,-8.210,1.0,0.0385,84.989,0.7610,37.0,285186.0,"-23.6,-46.6",18.00,0.1

<h3 style='color:gray;'>Imports Library JSON file, using record_path (1/2)</h3>

In [18]:
library = import_json(PATH_LIBRARY, record_path=['tracks'])
library.head()

,artist,album,track,uri
0,Set It Off,Wolf In Sheep's Clothing [REBORN],Wolf In Sheep's Clothing [REBORN],spotify:track:1tpidJ4FBn9TwshePh1bc3
1,Skillet,Awake,Monster,spotify:track:2UREu1Y8CO4jXkbvqAtP7g
2,Thousand Foot Krutch,The End Is Where We Begin,Courtesy Call,spotify:track:0AOmbw8AwDnwXhHC3OhdVB

<h3 style='color:gray;'>Imports Playlist JSON file, using extra method (2/2)</h3>

In [19]:
def transform_playlist(data):
    all_playlists = []
    for i in data['playlists']:
        i_playlist = pd.json_normalize(i['items'], sep='_')
        i_playlist['playlists_lastModifiedDate'] = i['lastModifiedDate']
        i_playlist['playlists_name'] = i['name']
        all_playlists.append(i_playlist)
    return pd.concat(all_playlists)

playlist = import_json(PATH_PLAYLIST, transform=transform_playlist)
playlist.head()

,episode,audiobook,local_track,added_date,track_track_name,track_artist_name,track_album_name,track_track_uri,track,episode_episode_name,episode_show_name,episode_episode_uri,playlists_last_modified_date,playlists_name
0,NaN,None,None,2024-10-22,Angry Too,Lola Blanc,Angry Too,spotify:track:51jK7uI2QR8JCP4G9DnbQS,NaN,NaN,NaN,NaN,2026-01-18,<3
1,NaN,None,None,2024-10-22,Walls Could Talk,Halsey,hopeless fountain kingdom,spotify:track:1Ao5nOuAUm42ob1UVvOkgW,NaN,NaN,NaN,NaN,2026-01-18,<3
2,NaN,None,None,2024-10-22,Freak (feat. REI AMI),Sub Urban,Thrill Seeker,spotify:track:5jkbw3FDS3bSSb4oLKYbjf,NaN,NaN,NaN,NaN,2026-01-18,<3
3,NaN,None,None,2024-10-22,Shameless,Camila Cabello,Romance,spotify:track:2ogKhhoMClkFXek7ZgxAhN,NaN,NaN,NaN,NaN,2026-01-18,<3
4,NaN,None,None,2024-10-22,Looking at Me,Sabrina Carpenter,Singular Act II,spotify:track:59tskctgqUmjCWAwhzYAFm,NaN,NaN,NaN,NaN,2026-01-18,<3

In [20]:
# 3. Convert lookup series to Python sets, before creating boolean columns
playlist_uris = set(playlist['track_track_uri'].dropna())
library_uris = set(library['uri'].dropna())

final_df['in_playlist'] = final_df['spotify_track_uri'].isin(playlist_uris)
final_df['in_library'] = final_df['spotify_track_uri'].isin(library_uris)

# creating playlist_percentage

In [21]:
#get total amount of playlist
playlist_amount = playlist['playlists_name'].nunique()

# 1. Get the counts of each value in df_2
counts = playlist['track_track_uri'].value_counts()

# 2. Map those counts to df_1
final_df['playlist_count'] = final_df['spotify_track_uri'].map(counts)

# 3. Fill NaNs with 0 (for values that didn't appear in df_2) and convert to integer
final_df['playlist_count'] = final_df['playlist_count'].fillna(0).astype(int)

final_df['percentage_playlists'] = final_df['playlist_count'] / playlist_amount

final_df

,Unnamed: 0,ts,platform,ms_played,conn_country,ip_addr,master_metadata_track_name,master_metadata_album_album_name,spotify_track_uri,episode_name,...,valence,popularity,duration_ms,lat_long,temperature,precipitation,in_playlist,in_library,playlist_count,percentage_playlists
0,0,2020-10-20 19:36:53+00:00,"Android OS 10 API 29 (samsung, SM-A307GT)",23600,BR,177.58.181.120,Pretty Savage,THE ALBUM,spotify:track:1XnpzbOGptRwfJhZgLbmSr,NaN,...,NaN,NaN,NaN,"-23.5,-46.3",23.00,0.8,False,False,0,0.0
1,1,2020-10-20 19:36:55+00:00,"Android OS 10 API 29 (samsung, SM-A307GT)",1052,BR,177.58.181.120,How You Like That,THE ALBUM,spotify:track:4SFknyjLcyTLJFPKD2m96o,NaN,...,NaN,NaN,NaN,"-23.5,-46.3",23.00,0.8,False,False,0,0.0
2,2,2020-10-20 19:36:56+00:00,"Android OS 10 API 29 (samsung, SM-A307GT)",0,BR,177.58.181.120,Ice Cream (with Selena Gomez),THE ALBUM,spotify:track:4JUPEh2DVSXFGExu4Uxevz,NaN,...,NaN,NaN,NaN,"-23.5,-46.3",23.00,0.8,False,False,0,0.0
3,3,2020-10-20 19:36:56+00:00,"Android OS 10 API 29 (samsung, SM-A307GT)",0,BR,177.58.181.120,Bet You Wanna (feat. Cardi B),THE ALBUM,spotify:track:7iAgNZdotu40NwtoIWJHFe,NaN,...,NaN,NaN,NaN,"-23.5,-46.3",23.00,0.8,False,False,0,0.0
4,4,2020-10-20 19:36:59+00:00,"Android OS 10 API 29 (samsung, SM-A307GT)",1824,BR,177.58.181.120,Lovesick Girls,THE ALBUM,spotify:track:4Ws314Ylb27BVsvlZOy30C,NaN,...,NaN,NaN,NaN,"-23.5,-46.3",23.00,0.8,False,False,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10887,10887,2026-01-22 20:56:53+00:00,ios,296853,BR,2804:7f0:b2c1:40d5:9512:4b9f:c178:1ce0,Friska from Hungarian Rhapsody No. 2,Autobahn [Drive Time],spotify:track:3B84LG8ayDrYnfwlm11Vn4,NaN,...,0.3600,24.0,296853.0,"-23.6,-46.6",17.55,0.3,False,False,0,0.0
10888,10888,2026-01-23 03:10:40+00:00,ios,437017,BR,2804:7f0:b2c1:40d5:38c4:1dd8:42d3:546d,Toccata and Fugue in D minor,Great Organ Classics,spotify:track:0BWJNm4TrO6H3qgiCmDBjM,NaN,...,0.0714,52.0,567466.0,"-23.6,-46.6",16.10,0.0,False,False,0,0.0
10889,10889,2026-01-23 13:13:29+00:00,ios,11685,BR,2804:38a:a08e:d9a5:7dbf:86aa:23b2:662f,Tis so Sweet to Trust in Jesus,Lullaby Hymns: The Weary Soul,spotify:track:21fL1tPW9PN7mgqhgeL7lC,NaN,...,0.1580,39.0,256653.0,"-23.5,-46.6",21.20,0.4,False,False,0,0.0
10890,10890,2026-01-23 13:13:29+00:00,ios,11685,BR,2804:38a:a08e:d9a5:7dbf:86aa:23b2:662f,Tis so Sweet to Trust in Jesus,Lullaby Hymns: The Weary Soul,spotify:track:21fL1tPW9PN7mgqhgeL7lC,NaN,...,0.1580,39.0,256653.0,"-23.5,-46.6",21.20,0.4,False,False,0,0.0
10891,10891,2026-01-24 03:50:37+00:00,ios,9590,BR,2804:7f0:b2c1:40d5:8950:9dc2:a0df:9123,Leaning On The Everlasting Arms / 'Tis So Swee...,Give Us Rest Or A Requiem Mass In C (The Happi...,spotify:track:2VAtZmI9nCB97Kdnn9tMIF,NaN,...,0.7610,37.0,285186.0,"-23.6,-46.6",18.00,0.1,False,False,0,0.0

# Creating next_track column

In [22]:
final_df['ts'] = pd.to_datetime(final_df['ts'])
final_df = final_df.sort_values('ts')
final_df['next_track'] = final_df['track_id'].shift(-1)
final_df

,Unnamed: 0,ts,platform,ms_played,conn_country,ip_addr,master_metadata_track_name,master_metadata_album_album_name,spotify_track_uri,episode_name,...,popularity,duration_ms,lat_long,temperature,precipitation,in_playlist,in_library,playlist_count,percentage_playlists,next_track
0,0,2020-10-20 19:36:53+00:00,"Android OS 10 API 29 (samsung, SM-A307GT)",23600,BR,177.58.181.120,Pretty Savage,THE ALBUM,spotify:track:1XnpzbOGptRwfJhZgLbmSr,NaN,...,NaN,NaN,"-23.5,-46.3",23.00,0.8,False,False,0,0.0,4SFknyjLcyTLJFPKD2m96o
1,1,2020-10-20 19:36:55+00:00,"Android OS 10 API 29 (samsung, SM-A307GT)",1052,BR,177.58.181.120,How You Like That,THE ALBUM,spotify:track:4SFknyjLcyTLJFPKD2m96o,NaN,...,NaN,NaN,"-23.5,-46.3",23.00,0.8,False,False,0,0.0,4JUPEh2DVSXFGExu4Uxevz
2,2,2020-10-20 19:36:56+00:00,"Android OS 10 API 29 (samsung, SM-A307GT)",0,BR,177.58.181.120,Ice Cream (with Selena Gomez),THE ALBUM,spotify:track:4JUPEh2DVSXFGExu4Uxevz,NaN,...,NaN,NaN,"-23.5,-46.3",23.00,0.8,False,False,0,0.0,7iAgNZdotu40NwtoIWJHFe
3,3,2020-10-20 19:36:56+00:00,"Android OS 10 API 29 (samsung, SM-A307GT)",0,BR,177.58.181.120,Bet You Wanna (feat. Cardi B),THE ALBUM,spotify:track:7iAgNZdotu40NwtoIWJHFe,NaN,...,NaN,NaN,"-23.5,-46.3",23.00,0.8,False,False,0,0.0,4Ws314Ylb27BVsvlZOy30C
4,4,2020-10-20 19:36:59+00:00,"Android OS 10 API 29 (samsung, SM-A307GT)",1824,BR,177.58.181.120,Lovesick Girls,THE ALBUM,spotify:track:4Ws314Ylb27BVsvlZOy30C,NaN,...,NaN,NaN,"-23.5,-46.3",23.00,0.8,False,False,0,0.0,4JUPEh2DVSXFGExu4Uxevz
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10887,10887,2026-01-22 20:56:53+00:00,ios,296853,BR,2804:7f0:b2c1:40d5:9512:4b9f:c178:1ce0,Friska from Hungarian Rhapsody No. 2,Autobahn [Drive Time],spotify:track:3B84LG8ayDrYnfwlm11Vn4,NaN,...,24.0,296853.0,"-23.6,-46.6",17.55,0.3,False,False,0,0.0,0BWJNm4TrO6H3qgiCmDBjM
10888,10888,2026-01-23 03:10:40+00:00,ios,437017,BR,2804:7f0:b2c1:40d5:38c4:1dd8:42d3:546d,Toccata and Fugue in D minor,Great Organ Classics,spotify:track:0BWJNm4TrO6H3qgiCmDBjM,NaN,...,52.0,567466.0,"-23.6,-46.6",16.10,0.0,False,False,0,0.0,21fL1tPW9PN7mgqhgeL7lC
10890,10890,2026-01-23 13:13:29+00:00,ios,11685,BR,2804:38a:a08e:d9a5:7dbf:86aa:23b2:662f,Tis so Sweet to Trust in Jesus,Lullaby Hymns: The Weary Soul,spotify:track:21fL1tPW9PN7mgqhgeL7lC,NaN,...,39.0,256653.0,"-23.5,-46.6",21.20,0.4,False,False,0,0.0,21fL1tPW9PN7mgqhgeL7lC
10889,10889,2026-01-23 13:13:29+00:00,ios,11685,BR,2804:38a:a08e:d9a5:7dbf:86aa:23b2:662f,Tis so Sweet to Trust in Jesus,Lullaby Hymns: The Weary Soul,spotify:track:21fL1tPW9PN7mgqhgeL7lC,NaN,...,39.0,256653.0,"-23.5,-46.6",21.20,0.4,False,False,0,0.0,2VAtZmI9nCB97Kdnn9tMIF
10891,10891,2026-01-24 03:50:37+00:00,ios,9590,BR,2804:7f0:b2c1:40d5:8950:9dc2:a0df:9123,Leaning On The Everlasting Arms / 'Tis So Swee...,Give Us Rest Or A Requiem Mass In C (The Happi...,spotify:track:2VAtZmI9nCB97Kdnn9tMIF,NaN,...,37.0,285186.0,"-23.6,-46.6",18.00,0.1,False,False,0,0.0,NaN

### Adding percentage_listened column

In [23]:
final_df['percentage_played'] = (final_df['ms_played'] / final_df['duration_ms']).round(4)

# Droping columns

In [24]:
columns_to_drop = [
    "ip_addr",
    "spotify_track_uri",
    "episode_name",
    "episode_show_name",
    "spotify_episode_uri",
    "audiobook_title",
    "audiobook_uri",
    "audiobook_chapter_uri",
    "audiobook_chapter_title",
    "offline_timestamp",
    "in_playlist",
    "lat_long",
    "track_id",
    "ms_played",
    "duration_ms",
    "Unnamed: 0",
    "platform"
    ]

for i in columns_to_drop:
    try:
        final_df = final_df.drop(columns=i)
    except:
        print(f"A coluna {i} não existe no final_df")
final_df.columns

Index(['ts', 'conn_country', 'master_metadata_track_name',
       'master_metadata_album_album_name', 'reason_start', 'reason_end',
       'shuffle', 'skipped', 'offline', 'incognito_mode', 'artist_name',
       'segment', 'acousticness', 'danceability', 'energy', 'instrumentalness',
       'key', 'liveness', 'loudness', 'mode', 'speechiness', 'tempo',
       'valence', 'popularity', 'temperature', 'precipitation', 'in_library',
       'playlist_count', 'percentage_playlists', 'next_track',
       'percentage_played'],
      dtype='str')

# Droping NAs

In [25]:
# Drops any row where at least one element is missing
not_na_df = final_df.dropna(how='any')
not_na_df

,ts,conn_country,master_metadata_track_name,master_metadata_album_album_name,reason_start,reason_end,shuffle,skipped,offline,incognito_mode,...,tempo,valence,popularity,temperature,precipitation,in_library,playlist_count,percentage_playlists,next_track,percentage_played
10,2020-10-23 19:52:08+00:00,BR,I'm Gonna Show You Crazy,I'm Gonna Show You Crazy,clickrow,endplay,False,False,False,False,...,90.103,0.335,56.0,22.40,0.1,False,1,1.0,5LtNBCM2ve0SxP0dlRVvMu,0.0051
9,2020-10-23 19:52:08+00:00,BR,I'm Gonna Show You Crazy,I'm Gonna Show You Crazy,clickrow,endplay,False,False,False,False,...,90.103,0.335,56.0,22.40,0.1,False,1,1.0,5LtNBCM2ve0SxP0dlRVvMu,0.0051
11,2020-10-23 19:55:36+00:00,BR,I'm Gonna Show You Crazy,I'm Gonna Show You Crazy,clickrow,trackdone,False,False,False,False,...,90.103,0.335,56.0,22.40,0.1,False,1,1.0,5LtNBCM2ve0SxP0dlRVvMu,1.0000
12,2020-10-23 19:55:36+00:00,BR,I'm Gonna Show You Crazy,I'm Gonna Show You Crazy,clickrow,trackdone,False,False,False,False,...,90.103,0.335,56.0,22.40,0.1,False,1,1.0,04ZTP5KsCypmtCmQg5tH9R,1.0000
13,2020-10-23 19:55:54+00:00,BR,I'm a Mess,Expectations,playbtn,endplay,False,False,False,False,...,97.005,0.216,68.0,22.40,0.1,False,1,1.0,04ZTP5KsCypmtCmQg5tH9R,0.0801
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10875,2026-01-21 13:52:42+00:00,BR,If U Seek Amy,Circus (Deluxe Version),trackdone,trackdone,True,False,False,False,...,129.954,0.544,69.0,18.90,5.9,False,1,1.0,2hdy9Wt9qp7M7d0U3ossu2,1.0012
10876,2026-01-21 13:52:42+00:00,BR,If U Seek Amy,Circus (Deluxe Version),trackdone,trackdone,True,False,False,False,...,129.954,0.544,69.0,18.90,5.9,False,1,1.0,1R1ihosU2CSEaSw8e5ZF6E,1.0012
10877,2026-01-21 17:27:15+00:00,BR,Ancient Dreams in a Modern Land,Ancient Dreams In A Modern Land,trackdone,logout,True,False,False,False,...,137.915,0.638,61.0,19.20,0.0,False,1,1.0,1R1ihosU2CSEaSw8e5ZF6E,0.0164
10878,2026-01-21 17:27:15+00:00,BR,Ancient Dreams in a Modern Land,Ancient Dreams In A Modern Land,trackdone,logout,True,False,False,False,...,137.915,0.638,61.0,19.20,0.0,False,1,1.0,1R1ihosU2CSEaSw8e5ZF6E,0.0164
10879,2026-01-22 20:17:04+00:00,BR,Ancient Dreams in a Modern Land,Ancient Dreams In A Modern Land,appload,endplay,True,True,False,False,...,137.915,0.638,61.0,17.55,0.3,False,1,1.0,1WBagB7FdOlxUpYTG9XVik,0.3680

# Droping duplicates

In [26]:
clean_df = not_na_df.drop_duplicates()

# Export Df

In [27]:
clean_df.to_csv(PATH_PROCESSED, index=False)